services:
  opensearch:
    extends:
      file: docker-compose.base.yml
      service: opensearch
    container_name: opensearch

  neo4j:
    extends:
      file: docker-compose.base.yml
      service: neo4j
    container_name: neo4j
